"""Seed definitions for 20 fictional/demo NGOs with realistic services, coverage, and historical contributions."""

DEMO_DISCLAIMER = "[DEMO/SEED DATA] Fictional organization created for demonstration and testing purposes. Not a real entity."

SEED_NGOS = [
    {
        "ngo_code": "NGO001",
        "ngo_name": "Helping Hands Foundation",
        "registration_number": "REG-2018-HH-001",
        "contact_person": "Aarav Sharma",
        "phone": "+91-9876543210",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "address": "12/4 MG Road, Bengaluru, Karnataka 560001",
        "description": f"Focuses on digital literacy, education, and student empowerment. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "EDUCATION", "requirement": "LAPTOP_DESKTOP", "quantity": 25, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "EDUCATION", "requirement": "TABLET", "quantity": 40, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "EDUCATION", "requirement": "BOOKS_STUDY_MATERIAL", "quantity": 500, "unit": "sets", "duration_val": 1, "duration_unit": "DAYS"},
            {"category": "EDUCATION", "requirement": "SCHOOL_SUPPLIES", "quantity": 300, "unit": "kits", "duration_val": 1, "duration_unit": "DAYS"},
            {"category": "DIGITAL_ACCESS", "requirement": "LAPTOP_DESKTOP", "quantity": 20, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "DIGITAL_ACCESS", "requirement": "COMPUTER_ACCESSORIES", "quantity": 50, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "DIGITAL_ACCESS", "requirement": "INTERNET_DEVICE", "quantity": 20, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Karnataka", "district": "Bengaluru Urban", "area": "Indiranagar"},
            {"state": "Karnataka", "district": "Bengaluru Urban", "area": "Whitefield"},
            {"state": "Karnataka", "district": "Mysuru", "area": "Chamundipuram"},
            {"state": "Tamil Nadu", "district": "Chennai", "area": "Adyar"},
        ],
        "history_profile": {"completed_count": 84, "beneficiaries_base": 620, "quantity_base": 1450, "on_time_pct": 96.0, "req_code": "LAPTOP_DESKTOP"},
    },
    {
        "ngo_code": "NGO002",
        "ngo_name": "Rural Development Trust",
        "registration_number": "REG-2015-RDT-002",
        "contact_person": "Venkatesh Rao",
        "phone": "+91-9876543211",
        "state": "Andhra Pradesh",
        "district": "Anantapur",
        "address": "45 Court Road, Anantapur, Andhra Pradesh 515001",
        "description": f"Dedicated to rural infrastructure, farming inputs, and community water solutions. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "AGRICULTURE", "requirement": "SEEDS", "quantity": 200, "unit": "bags", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "AGRICULTURE", "requirement": "WATER_PUMP", "quantity": 15, "unit": "units", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "AGRICULTURE", "requirement": "IRRIGATION_EQUIPMENT", "quantity": 25, "unit": "kits", "duration_val": 4, "duration_unit": "DAYS"},
            {"category": "WATER_SANITATION", "requirement": "WATER_FILTER", "quantity": 40, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "WATER_SANITATION", "requirement": "WATER_TANK", "quantity": 20, "unit": "tanks", "duration_val": 5, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Andhra Pradesh", "district": "Anantapur", "area": "Dharmavaram"},
            {"state": "Andhra Pradesh", "district": "Anantapur", "area": "Kadiri"},
            {"state": "Andhra Pradesh", "district": "Kurnool", "area": "Adoni"},
        ],
        "history_profile": {"completed_count": 92, "beneficiaries_base": 840, "quantity_base": 1100, "on_time_pct": 92.0, "req_code": "SEEDS"},
    },
    {
        "ngo_code": "NGO003",
        "ngo_name": "Fisher Welfare Foundation",
        "registration_number": "REG-2016-FWF-003",
        "contact_person": "Muruganandham S",
        "phone": "+91-9876543212",
        "state": "Tamil Nadu",
        "district": "Nagapattinam",
        "address": "78 Harbour Road, Nagapattinam, Tamil Nadu 611001",
        "description": f"Specialized in coastal community livelihood and fishing apparatus provisioning. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "FISHERIES", "requirement": "FISHING_NET", "quantity": 50, "unit": "nets", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "FISHERIES", "requirement": "FISHING_BOAT", "quantity": 5, "unit": "boats", "duration_val": 14, "duration_unit": "DAYS"},
            {"category": "FISHERIES", "requirement": "BOAT_ENGINE", "quantity": 8, "unit": "engines", "duration_val": 7, "duration_unit": "DAYS"},
            {"category": "FISHERIES", "requirement": "FISHING_GEAR", "quantity": 40, "unit": "kits", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "FISHERIES", "requirement": "SAFETY_EQUIPMENT", "quantity": 100, "unit": "kits", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "FISHERIES", "requirement": "FISH_STORAGE_EQUIPMENT", "quantity": 20, "unit": "units", "duration_val": 4, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Tamil Nadu", "district": "Nagapattinam", "area": "Velankanni"},
            {"state": "Tamil Nadu", "district": "Nagapattinam", "area": "Nagapattinam"},
            {"state": "Tamil Nadu", "district": "Nagapattinam", "area": "Vedaranyam"},
            {"state": "Tamil Nadu", "district": "Thiruvarur", "area": "Muthupet"},
        ],
        "history_profile": {"completed_count": 145, "beneficiaries_base": 1180, "quantity_base": 1250, "on_time_pct": 94.0, "req_code": "FISHING_NET"},
    },
    {
        "ngo_code": "NGO004",
        "ngo_name": "Care India Foundation",
        "registration_number": "REG-2014-CIF-004",
        "contact_person": "Dr. Sunita Deshmukh",
        "phone": "+91-9876543213",
        "state": "Maharashtra",
        "district": "Pune",
        "address": "101 Shivajinagar, Pune, Maharashtra 411005",
        "description": f"Provides comprehensive medical aid, diagnostics, and disability mobility equipment. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "HEALTHCARE", "requirement": "MEDICINES", "quantity": 500, "unit": "kits", "duration_val": 1, "duration_unit": "DAYS"},
            {"category": "HEALTHCARE", "requirement": "MEDICAL_EQUIPMENT", "quantity": 30, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "HEALTHCARE", "requirement": "WHEELCHAIR", "quantity": 20, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "HEALTHCARE", "requirement": "HEARING_AID", "quantity": 15, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "HEALTHCARE", "requirement": "DIAGNOSTIC_SUPPORT", "quantity": 100, "unit": "beneficiaries", "duration_val": 1, "duration_unit": "DAYS"},
            {"category": "HEALTHCARE", "requirement": "MEDICAL_TREATMENT", "quantity": 50, "unit": "beneficiaries", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "DISABILITY", "requirement": "WALKING_AID", "quantity": 30, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "DISABILITY", "requirement": "REHABILITATION_SUPPORT", "quantity": 80, "unit": "beneficiaries", "duration_val": 7, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Maharashtra", "district": "Pune", "area": "Haveli"},
            {"state": "Maharashtra", "district": "Pune", "area": "Baramati"},
            {"state": "Maharashtra", "district": "Satara", "area": "Karad"},
            {"state": "Maharashtra", "district": "Mumbai Suburban", "area": "Andheri"},
        ],
        "history_profile": {"completed_count": 72, "beneficiaries_base": 500, "quantity_base": 400, "on_time_pct": 91.0, "req_code": "WHEELCHAIR"},
    },
    {
        "ngo_code": "NGO005",
        "ngo_name": "Bright Future Foundation",
        "registration_number": "REG-2019-BFF-005",
        "contact_person": "Priya Nair",
        "phone": "+91-9876543214",
        "state": "Kerala",
        "district": "Ernakulam",
        "address": "22 Marine Drive, Kochi, Kerala 682031",
        "description": f"Youth empowerment, educational tech, and digital vocational skill trainings. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "EDUCATION", "requirement": "LAPTOP_DESKTOP", "quantity": 15, "unit": "units", "duration_val": 4, "duration_unit": "DAYS"},
            {"category": "EDUCATION", "requirement": "TABLET", "quantity": 30, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "EDUCATION", "requirement": "BOOKS_STUDY_MATERIAL", "quantity": 400, "unit": "sets", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "EDUCATION", "requirement": "EDUCATIONAL_EQUIPMENT", "quantity": 20, "unit": "units", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "EDUCATION", "requirement": "EDUCATIONAL_TRAINING", "quantity": 100, "unit": "beneficiaries", "duration_val": 10, "duration_unit": "DAYS"},
            {"category": "SKILL_DEVELOPMENT", "requirement": "COMPUTER_TRAINING", "quantity": 80, "unit": "beneficiaries", "duration_val": 14, "duration_unit": "DAYS"},
            {"category": "SKILL_DEVELOPMENT", "requirement": "SEWING_TRAINING", "quantity": 50, "unit": "beneficiaries", "duration_val": 14, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Kerala", "district": "Ernakulam", "area": "Aluva"},
            {"state": "Kerala", "district": "Ernakulam", "area": "Kakkanad"},
            {"state": "Kerala", "district": "Thrissur", "area": "Chalakudy"},
            {"state": "Tamil Nadu", "district": "Coimbatore", "area": "Gandhipuram"},
        ],
        "history_profile": {"completed_count": 68, "beneficiaries_base": 780, "quantity_base": 820, "on_time_pct": 95.0, "req_code": "LAPTOP_DESKTOP"},
    },
    {
        "ngo_code": "NGO006",
        "ngo_name": "Women Rise Foundation",
        "registration_number": "REG-2017-WRF-006",
        "contact_person": "Meenakshi Sundaram",
        "phone": "+91-9876543215",
        "state": "Tamil Nadu",
        "district": "Madurai",
        "address": "89 West Masi Street, Madurai, Tamil Nadu 625001",
        "description": f"Micro-enterprise promotion, sewing machines, and livelihood tools for women. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "WOMEN_EMPOWERMENT", "requirement": "SEWING_MACHINE", "quantity": 60, "unit": "machines", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "WOMEN_EMPOWERMENT", "requirement": "BUSINESS_EQUIPMENT", "quantity": 30, "unit": "kits", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "WOMEN_EMPOWERMENT", "requirement": "SKILL_TRAINING", "quantity": 120, "unit": "beneficiaries", "duration_val": 14, "duration_unit": "DAYS"},
            {"category": "LIVELIHOOD", "requirement": "SEWING_MACHINE", "quantity": 40, "unit": "machines", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "LIVELIHOOD", "requirement": "BUSINESS_STARTER_KIT", "quantity": 25, "unit": "kits", "duration_val": 4, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Tamil Nadu", "district": "Madurai", "area": "Melur"},
            {"state": "Tamil Nadu", "district": "Madurai", "area": "Thirumangalam"},
            {"state": "Tamil Nadu", "district": "Dindigul", "area": "Palani"},
        ],
        "history_profile": {"completed_count": 110, "beneficiaries_base": 950, "quantity_base": 1050, "on_time_pct": 93.5, "req_code": "SEWING_MACHINE"},
    },
    {
        "ngo_code": "NGO007",
        "ngo_name": "Green Earth Foundation",
        "registration_number": "REG-2020-GEF-007",
        "contact_person": "Rohan Mukherjee",
        "phone": "+91-9876543216",
        "state": "West Bengal",
        "district": "Kolkata",
        "address": "15 Park Street, Kolkata, West Bengal 700016",
        "description": f"Afforestation, organic waste composting, and environmental preservation initiatives. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "ENVIRONMENT", "requirement": "SAPLINGS", "quantity": 2000, "unit": "saplings", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "ENVIRONMENT", "requirement": "GARDENING_EQUIPMENT", "quantity": 80, "unit": "kits", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "ENVIRONMENT", "requirement": "COMPOSTING_EQUIPMENT", "quantity": 30, "unit": "units", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "ENVIRONMENT", "requirement": "RAINWATER_HARVESTING_EQUIPMENT", "quantity": 15, "unit": "kits", "duration_val": 7, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "West Bengal", "district": "Kolkata", "area": "Salt Lake"},
            {"state": "West Bengal", "district": "North 24 Parganas", "area": "Barasat"},
            {"state": "West Bengal", "district": "South 24 Parganas", "area": "Sonarpur"},
        ],
        "history_profile": {"completed_count": 55, "beneficiaries_base": 1200, "quantity_base": 3500, "on_time_pct": 89.0, "req_code": "SAPLINGS"},
    },
    {
        "ngo_code": "NGO008",
        "ngo_name": "Digital Hope Foundation",
        "registration_number": "REG-2021-DHF-008",
        "contact_person": "Ananya Sen",
        "phone": "+91-9876543217",
        "state": "Telangana",
        "district": "Hyderabad",
        "address": "504 Hitech City, Hyderabad, Telangana 500081",
        "description": f"Bridging the digital divide with refurbished computers and connected hardware. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "DIGITAL_ACCESS", "requirement": "LAPTOP_DESKTOP", "quantity": 40, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "DIGITAL_ACCESS", "requirement": "TABLET", "quantity": 50, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "DIGITAL_ACCESS", "requirement": "SMARTPHONE", "quantity": 30, "unit": "units", "duration_val": 1, "duration_unit": "DAYS"},
            {"category": "EDUCATION", "requirement": "LAPTOP_DESKTOP", "quantity": 35, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Telangana", "district": "Hyderabad", "area": "Madhapur"},
            {"state": "Telangana", "district": "Rangareddy", "area": "Gachibowli"},
            {"state": "Andhra Pradesh", "district": "Visakhapatnam", "area": "MVP Colony"},
        ],
        "history_profile": {"completed_count": 60, "beneficiaries_base": 450, "quantity_base": 520, "on_time_pct": 97.0, "req_code": "LAPTOP_DESKTOP"},
    },
    {
        "ngo_code": "NGO009",
        "ngo_name": "Coastal Livelihood Trust",
        "registration_number": "REG-2016-CLT-009",
        "contact_person": "K. Balakrishnan",
        "phone": "+91-9876543218",
        "state": "Tamil Nadu",
        "district": "Nagapattinam",
        "address": "14 Beach Road, Nagapattinam, Tamil Nadu 611001",
        "description": f"Coastal resilience, marine fishing tools, and disaster recovery support. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "FISHERIES", "requirement": "FISHING_NET", "quantity": 100, "unit": "nets", "duration_val": 4, "duration_unit": "DAYS"},
            {"category": "FISHERIES", "requirement": "FISHING_GEAR", "quantity": 70, "unit": "kits", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "FISHERIES", "requirement": "SAFETY_EQUIPMENT", "quantity": 80, "unit": "kits", "duration_val": 1, "duration_unit": "DAYS"},
            {"category": "FISHERIES", "requirement": "FISH_STORAGE_EQUIPMENT", "quantity": 30, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "DISASTER_RECOVERY", "requirement": "LIVELIHOOD_RECOVERY_EQUIPMENT", "quantity": 40, "unit": "kits", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "DISASTER_RECOVERY", "requirement": "HOUSE_REPAIR_MATERIALS", "quantity": 30, "unit": "kits", "duration_val": 4, "duration_unit": "DAYS"},
            {"category": "DISASTER_RECOVERY", "requirement": "SOLAR_LAMP", "quantity": 100, "unit": "units", "duration_val": 1, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Tamil Nadu", "district": "Nagapattinam", "area": "Nagapattinam"},
            {"state": "Puducherry", "district": "Karaikal", "area": "Karaikal Port"},
            {"state": "Tamil Nadu", "district": "Cuddalore", "area": "Portonovo"},
        ],
        "history_profile": {"completed_count": 130, "beneficiaries_base": 1100, "quantity_base": 1350, "on_time_pct": 95.0, "req_code": "FISHING_NET"},
    },
    {
        "ngo_code": "NGO010",
        "ngo_name": "Health Support Foundation",
        "registration_number": "REG-2018-HSF-010",
        "contact_person": "Dr. Rajiv Gupta",
        "phone": "+91-9876543219",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
        "address": "28 Hazratganj, Lucknow, Uttar Pradesh 226001",
        "description": f"Community health outreach, essential diagnostic kits, and medical wheelchairs. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "HEALTHCARE", "requirement": "MEDICINES", "quantity": 600, "unit": "kits", "duration_val": 1, "duration_unit": "DAYS"},
            {"category": "HEALTHCARE", "requirement": "WHEELCHAIR", "quantity": 35, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "HEALTHCARE", "requirement": "MEDICAL_EQUIPMENT", "quantity": 40, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "ELDERLY_SUPPORT", "requirement": "WALKING_AID", "quantity": 50, "unit": "units", "duration_val": 1, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Uttar Pradesh", "district": "Lucknow", "area": "Alambagh"},
            {"state": "Uttar Pradesh", "district": "Lucknow", "area": "Gomti Nagar"},
            {"state": "Uttar Pradesh", "district": "Kanpur Nagar", "area": "Civil Lines"},
        ],
        "history_profile": {"completed_count": 78, "beneficiaries_base": 890, "quantity_base": 920, "on_time_pct": 90.0, "req_code": "MEDICINES"},
    },
    {
        "ngo_code": "NGO011",
        "ngo_name": "Rural Skills Foundation",
        "registration_number": "REG-2019-RSF-011",
        "contact_person": "Manish Patel",
        "phone": "+91-9876543220",
        "state": "Gujarat",
        "district": "Ahmedabad",
        "address": "104 Ashram Road, Ahmedabad, Gujarat 380009",
        "description": f"Skilling rural youth in technical trades and vocational certifications. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "SKILL_DEVELOPMENT", "requirement": "ELECTRICAL_TRAINING", "quantity": 60, "unit": "beneficiaries", "duration_val": 21, "duration_unit": "DAYS"},
            {"category": "SKILL_DEVELOPMENT", "requirement": "WELDING_TRAINING", "quantity": 40, "unit": "beneficiaries", "duration_val": 21, "duration_unit": "DAYS"},
            {"category": "LIVELIHOOD", "requirement": "TOOL_KIT", "quantity": 80, "unit": "kits", "duration_val": 3, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Gujarat", "district": "Ahmedabad", "area": "Sanand"},
            {"state": "Gujarat", "district": "Gandhinagar", "area": "Kalol"},
            {"state": "Gujarat", "district": "Vadodara", "area": "Makarpura"},
        ],
        "history_profile": {"completed_count": 65, "beneficiaries_base": 520, "quantity_base": 600, "on_time_pct": 92.0, "req_code": "TOOL_KIT"},
    },
    {
        "ngo_code": "NGO012",
        "ngo_name": "Child Development Trust",
        "registration_number": "REG-2015-CDT-012",
        "contact_person": "Kavita Reddy",
        "phone": "+91-9876543221",
        "state": "Telangana",
        "district": "Warangal",
        "address": "12 Subedari, Warangal, Telangana 506001",
        "description": f"Dedicated to child education, learning materials, and recreational equipment. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "CHILD_WELFARE", "requirement": "SCHOOL_SUPPLIES", "quantity": 500, "unit": "kits", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "CHILD_WELFARE", "requirement": "BOOKS_STUDY_MATERIAL", "quantity": 600, "unit": "sets", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "CHILD_WELFARE", "requirement": "SCHOOL_UNIFORM", "quantity": 300, "unit": "sets", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "CHILD_WELFARE", "requirement": "SPORTS_EQUIPMENT", "quantity": 40, "unit": "kits", "duration_val": 3, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Telangana", "district": "Warangal", "area": "Hanamkonda"},
            {"state": "Telangana", "district": "Warangal", "area": "Kazipet"},
            {"state": "Telangana", "district": "Karimnagar", "area": "Godavarikhani"},
        ],
        "history_profile": {"completed_count": 88, "beneficiaries_base": 1100, "quantity_base": 1400, "on_time_pct": 94.5, "req_code": "SCHOOL_SUPPLIES"},
    },
    {
        "ngo_code": "NGO013",
        "ngo_name": "Inclusive Life Foundation",
        "registration_number": "REG-2017-ILF-013",
        "contact_person": "Vikram Singh",
        "phone": "+91-9876543222",
        "state": "Rajasthan",
        "district": "Jaipur",
        "address": "77 MI Road, Jaipur, Rajasthan 302001",
        "description": f"Assistive technology, prosthetics, and accessibility devices for differently abled. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "DISABILITY", "requirement": "WHEELCHAIR", "quantity": 45, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "DISABILITY", "requirement": "PROSTHETIC_ORTHOTIC_DEVICE", "quantity": 25, "unit": "units", "duration_val": 10, "duration_unit": "DAYS"},
            {"category": "DISABILITY", "requirement": "HEARING_AID", "quantity": 30, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "MOBILITY", "requirement": "TRICYCLE", "quantity": 20, "unit": "units", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "MOBILITY", "requirement": "WHEELCHAIR", "quantity": 40, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Rajasthan", "district": "Jaipur", "area": "Mansarovar"},
            {"state": "Rajasthan", "district": "Jaipur", "area": "Vaishali Nagar"},
            {"state": "Rajasthan", "district": "Ajmer", "area": "Kishangarh"},
        ],
        "history_profile": {"completed_count": 95, "beneficiaries_base": 730, "quantity_base": 780, "on_time_pct": 93.0, "req_code": "WHEELCHAIR"},
    },
    {
        "ngo_code": "NGO014",
        "ngo_name": "Clean Water Initiative",
        "registration_number": "REG-2016-CWI-014",
        "contact_person": "Siddharth Das",
        "phone": "+91-9876543223",
        "state": "Odisha",
        "district": "Khordha",
        "address": "33 Janpath, Bhubaneswar, Odisha 751001",
        "description": f"Safe drinking water filtration, hygiene sanitation, and water storage solutions. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "WATER_SANITATION", "requirement": "WATER_FILTER", "quantity": 120, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "WATER_SANITATION", "requirement": "WATER_TANK", "quantity": 40, "unit": "units", "duration_val": 4, "duration_unit": "DAYS"},
            {"category": "WATER_SANITATION", "requirement": "TOILET_SUPPORT", "quantity": 25, "unit": "kits", "duration_val": 7, "duration_unit": "DAYS"},
            {"category": "WATER_SANITATION", "requirement": "WATER_PUMP", "quantity": 30, "unit": "units", "duration_val": 4, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Odisha", "district": "Khordha", "area": "Jatani"},
            {"state": "Odisha", "district": "Puri", "area": "Nimapada"},
            {"state": "Odisha", "district": "Cuttack", "area": "Choudwar"},
        ],
        "history_profile": {"completed_count": 105, "beneficiaries_base": 1400, "quantity_base": 1200, "on_time_pct": 94.0, "req_code": "WATER_FILTER"},
    },
    {
        "ngo_code": "NGO015",
        "ngo_name": "Solar Future Foundation",
        "registration_number": "REG-2019-SFF-015",
        "contact_person": "Harish Verma",
        "phone": "+91-9876543224",
        "state": "Madhya Pradesh",
        "district": "Bhopal",
        "address": "62 MP Nagar, Bhopal, Madhya Pradesh 462011",
        "description": f"Clean decentralized energy, rooftop solar systems, and emergency solar lamps. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "ENERGY", "requirement": "SOLAR_PANEL", "quantity": 50, "unit": "panels", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "ENERGY", "requirement": "SOLAR_LAMP", "quantity": 300, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "ENERGY", "requirement": "BATTERY_INVERTER", "quantity": 25, "unit": "units", "duration_val": 4, "duration_unit": "DAYS"},
            {"category": "ENERGY", "requirement": "LED_LIGHTING", "quantity": 500, "unit": "units", "duration_val": 1, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Madhya Pradesh", "district": "Bhopal", "area": "Kolar"},
            {"state": "Madhya Pradesh", "district": "Sehore", "area": "Ashta"},
            {"state": "Madhya Pradesh", "district": "Raisen", "area": "Mandideep"},
        ],
        "history_profile": {"completed_count": 82, "beneficiaries_base": 960, "quantity_base": 1800, "on_time_pct": 92.5, "req_code": "SOLAR_LAMP"},
    },
    {
        "ngo_code": "NGO016",
        "ngo_name": "Farmers Support Foundation",
        "registration_number": "REG-2015-FSF-016",
        "contact_person": "Gurpreet Singh",
        "phone": "+91-9876543225",
        "state": "Punjab",
        "district": "Ludhiana",
        "address": "90 GT Road, Ludhiana, Punjab 141001",
        "description": f"Smallholder farmer inputs, seeds, irrigation apparatus, and machinery. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "AGRICULTURE", "requirement": "SEEDS", "quantity": 400, "unit": "bags", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "AGRICULTURE", "requirement": "FARMING_TOOLS", "quantity": 150, "unit": "kits", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "AGRICULTURE", "requirement": "WATER_PUMP", "quantity": 35, "unit": "units", "duration_val": 4, "duration_unit": "DAYS"},
            {"category": "AGRICULTURE", "requirement": "FARM_MACHINERY", "quantity": 10, "unit": "units", "duration_val": 7, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Punjab", "district": "Ludhiana", "area": "Jagraon"},
            {"state": "Punjab", "district": "Patiala", "area": "Nabha"},
            {"state": "Haryana", "district": "Ambala", "area": "Barara"},
        ],
        "history_profile": {"completed_count": 115, "beneficiaries_base": 1350, "quantity_base": 1600, "on_time_pct": 96.0, "req_code": "SEEDS"},
    },
    {
        "ngo_code": "NGO017",
        "ngo_name": "Youth Sports Foundation",
        "registration_number": "REG-2020-YSF-017",
        "contact_person": "Sanjay Kapoor",
        "phone": "+91-9876543226",
        "state": "Haryana",
        "district": "Rohtak",
        "address": "40 Stadium Road, Rohtak, Haryana 124001",
        "description": f"Grassroots sports training, athletic equipment, and fitness mentorship for youth. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "SPORTS", "requirement": "SPORTS_EQUIPMENT", "quantity": 80, "unit": "kits", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "SPORTS", "requirement": "CRICKET_EQUIPMENT", "quantity": 50, "unit": "kits", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "SPORTS", "requirement": "FOOTBALL_EQUIPMENT", "quantity": 60, "unit": "kits", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "SPORTS", "requirement": "SPORTS_SHOES", "quantity": 200, "unit": "pairs", "duration_val": 3, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Haryana", "district": "Rohtak", "area": "Meham"},
            {"state": "Haryana", "district": "Sonipat", "area": "Gohana"},
            {"state": "Delhi", "district": "North West Delhi", "area": "Rohini"},
        ],
        "history_profile": {"completed_count": 48, "beneficiaries_base": 850, "quantity_base": 900, "on_time_pct": 91.5, "req_code": "SPORTS_EQUIPMENT"},
    },
    {
        "ngo_code": "NGO018",
        "ngo_name": "Shelter Support Trust",
        "registration_number": "REG-2016-SST-018",
        "contact_person": "Amitabh Roy",
        "phone": "+91-9876543227",
        "state": "Bihar",
        "district": "Patna",
        "address": "19 Boring Road, Patna, Bihar 800001",
        "description": f"Disaster shelter repair, roofing materials, and emergency bedding relief. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "HOUSING", "requirement": "ROOFING_MATERIALS", "quantity": 100, "unit": "sheets", "duration_val": 4, "duration_unit": "DAYS"},
            {"category": "HOUSING", "requirement": "BEDS_MATTRESSES", "quantity": 80, "unit": "sets", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "HOUSING", "requirement": "HOME_REPAIR_SUPPORT", "quantity": 30, "unit": "kits", "duration_val": 5, "duration_unit": "DAYS"},
            {"category": "DISASTER_RECOVERY", "requirement": "TEMPORARY_SHELTER", "quantity": 150, "unit": "tents", "duration_val": 2, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Bihar", "district": "Patna", "area": "Danapur"},
            {"state": "Bihar", "district": "Muzaffarpur", "area": "Kanti"},
            {"state": "Bihar", "district": "Vaishali", "area": "Hajipur"},
        ],
        "history_profile": {"completed_count": 76, "beneficiaries_base": 1150, "quantity_base": 1250, "on_time_pct": 89.5, "req_code": "ROOFING_MATERIALS"},
    },
    {
        "ngo_code": "NGO019",
        "ngo_name": "Women & Child Development Trust",
        "registration_number": "REG-2018-WCDT-019",
        "contact_person": "Shobha Rani",
        "phone": "+91-9876543228",
        "state": "Karnataka",
        "district": "Dharwad",
        "address": "5 PB Road, Hubballi, Karnataka 580029",
        "description": f"Empowering women artisans, child nutrition, and early schooling support. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "WOMEN_EMPOWERMENT", "requirement": "SEWING_MACHINE", "quantity": 50, "unit": "machines", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "WOMEN_EMPOWERMENT", "requirement": "DIGITAL_TRAINING", "quantity": 100, "unit": "beneficiaries", "duration_val": 14, "duration_unit": "DAYS"},
            {"category": "CHILD_WELFARE", "requirement": "SCHOOL_SUPPLIES", "quantity": 300, "unit": "kits", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "CHILD_WELFARE", "requirement": "LEARNING_SUPPORT", "quantity": 120, "unit": "beneficiaries", "duration_val": 30, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Karnataka", "district": "Dharwad", "area": "Hubballi"},
            {"state": "Karnataka", "district": "Belagavi", "area": "Gokak"},
            {"state": "Karnataka", "district": "Uttara Kannada", "area": "Sirsi"},
        ],
        "history_profile": {"completed_count": 86, "beneficiaries_base": 880, "quantity_base": 920, "on_time_pct": 93.0, "req_code": "SEWING_MACHINE"},
    },
    {
        "ngo_code": "NGO020",
        "ngo_name": "Community Care Foundation",
        "registration_number": "REG-2017-CCF-020",
        "contact_person": "Deepak Chawla",
        "phone": "+91-9876543229",
        "state": "Delhi",
        "district": "South Delhi",
        "address": "88 Saket Community Centre, New Delhi 110017",
        "description": f"Multi-sector urban welfare foundation supporting education, mobility, and elderly care. {DEMO_DISCLAIMER}",
        "registration_status": "APPROVED",
        "services": [
            {"category": "EDUCATION", "requirement": "LAPTOP_DESKTOP", "quantity": 30, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "HEALTHCARE", "requirement": "WHEELCHAIR", "quantity": 25, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "ELDERLY_SUPPORT", "requirement": "WHEELCHAIR", "quantity": 30, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
            {"category": "MOBILITY", "requirement": "BICYCLE", "quantity": 70, "unit": "units", "duration_val": 3, "duration_unit": "DAYS"},
            {"category": "MOBILITY", "requirement": "WHEELCHAIR", "quantity": 25, "unit": "units", "duration_val": 2, "duration_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Delhi", "district": "South Delhi", "area": "Saket"},
            {"state": "Delhi", "district": "South Delhi", "area": "Hauz Khas"},
            {"state": "Haryana", "district": "Gurugram", "area": "DLF Phase 3"},
            {"state": "Uttar Pradesh", "district": "Gautam Buddha Nagar", "area": "Noida Sector 62"},
        ],
        "history_profile": {"completed_count": 98, "beneficiaries_base": 1050, "quantity_base": 1150, "on_time_pct": 95.5, "req_code": "BICYCLE"},
    },
]
