"""Master Service Categories and Standardized Requirements definitions."""

MASTER_CATEGORIES = [
    {"code": "AGRICULTURE", "name": "Agriculture & Farming Support", "description": "Support for seeds, farming tools, irrigation equipment, and agricultural implements."},
    {"code": "FISHERIES", "name": "Fisheries & Marine Support", "description": "Support for fishing nets, boats, marine safety gear, and fish storage equipment."},
    {"code": "EDUCATION", "name": "Education & Student Aid", "description": "Support for laptops, tablets, books, school supplies, and educational material."},
    {"code": "HEALTHCARE", "name": "Healthcare & Medical Aid", "description": "Support for medicines, medical equipment, wheelchairs, hearing aids, and diagnostic support."},
    {"code": "DISABILITY", "name": "Disability & Assistive Tech", "description": "Assistive devices, wheelchairs, walking aids, prosthetic devices, and rehabilitation."},
    {"code": "LIVELIHOOD", "name": "Livelihood & Micro-Enterprise", "description": "Sewing machines, artisan toolkits, business starter kits, and livelihood equipment."},
    {"code": "WOMEN_EMPOWERMENT", "name": "Women Empowerment & Self-Help", "description": "Skill training kits, micro-business equipment, and self-help group resources."},
    {"code": "CHILD_WELFARE", "name": "Child Welfare & Nutrition", "description": "School kits, uniforms, learning aids, and nutritional supplements."},
    {"code": "ELDERLY_SUPPORT", "name": "Elderly Care & Geriatric Support", "description": "Mobility equipment, home care kits, and geriatric assistive products."},
    {"code": "HOUSING", "name": "Housing & Shelter Assistance", "description": "Roofing sheets, home repair materials, bedding, and emergency shelter items."},
    {"code": "WATER_SANITATION", "name": "Water & Sanitation Support", "description": "Water purifiers, storage tanks, water pumps, and sanitation equipment."},
    {"code": "ENERGY", "name": "Clean Energy & Lighting", "description": "Solar lamps, solar home lighting kits, inverters, and clean cooking solutions."},
    {"code": "DIGITAL_ACCESS", "name": "Digital Inclusion & Technology", "description": "Computers, internet access devices, smartphones, and digital literacy tools."},
    {"code": "DISASTER_RECOVERY", "name": "Disaster Relief & Rehabilitation", "description": "Emergency shelter kits, water purification tablets, and recovery packages."},
    {"code": "SKILL_DEVELOPMENT", "name": "Vocational Skills & Training", "description": "Training toolkits for electrical, tailoring, welding, and technical courses."},
    {"code": "MOBILITY", "name": "Mobility & Transport Support", "description": "Bicycles, tricycles, and accessible transport assistance."},
    {"code": "ENVIRONMENT", "name": "Environment & Green Living", "description": "Saplings, organic gardening kits, and waste management tools."},
    {"code": "SPORTS", "name": "Sports & Youth Development", "description": "Sports gear, football/cricket kits, and athletic equipment for youth."},
]

MASTER_REQUIREMENTS = {
    "AGRICULTURE": [
        {"code": "SEEDS", "name": "Certified Crop & Vegetable Seeds", "description": "High yield crop, vegetable, and pulse seeds."},
        {"code": "FARMING_TOOLS", "name": "Hand Farming Tools & Implements", "description": "Spades, sickles, ploughs, and weeding tools."},
        {"code": "IRRIGATION_EQUIPMENT", "name": "Drip / Sprinkler Irrigation Kit", "description": "Water-saving drip lines, nozzles, and pipes."},
        {"code": "WATER_PUMP", "name": "Solar / Diesel Water Pump", "description": "Agricultural water extraction pump."},
        {"code": "FARM_MACHINERY", "name": "Mini Tiller / Power Weeder", "description": "Small-scale mechanized farming machinery."},
        {"code": "LIVESTOCK_EQUIPMENT", "name": "Dairy & Cattle Care Equipment", "description": "Milking cans, chaff cutters, and feeding troughs."},
    ],
    "FISHERIES": [
        {"code": "FISHING_NET", "name": "Nylon Coastal / Marine Fishing Net", "description": "Monofilament and multifilament marine nets."},
        {"code": "FISHING_BOAT", "name": "Traditional / FRP Fishing Boat", "description": "Small-scale coastal and inland fishing craft."},
        {"code": "BOAT_ENGINE", "name": "Outboard / Inboard Marine Engine", "description": "Motor engine for fishing boats."},
        {"code": "FISHING_GEAR", "name": "Hooks, Lines & Fishing Gear", "description": "Complete line, hook, and float tackle."},
        {"code": "SAFETY_EQUIPMENT", "name": "Life Jackets & Marine GPS / Beacon", "description": "Safety gear and navigational distress beacons."},
        {"code": "FISH_STORAGE_EQUIPMENT", "name": "Insulated Ice Box / Cold Storage Box", "description": "Thermal ice containers for catch preservation."},
    ],
    "EDUCATION": [
        {"code": "LAPTOP_DESKTOP", "name": "Laptop / Desktop Computer", "description": "Computing device for higher education and vocational study."},
        {"code": "TABLET", "name": "Educational Learning Tablet", "description": "Android learning tablet with preloaded content."},
        {"code": "BOOKS_STUDY_MATERIAL", "name": "Curriculum Textbooks & Reference Books", "description": "School and college academic books."},
        {"code": "SCHOOL_SUPPLIES", "name": "Stationery & School Bag Kit", "description": "Notebooks, geometry box, bags, and writing materials."},
        {"code": "EDUCATIONAL_EQUIPMENT", "name": "STEM & Science Lab Kit", "description": "Practical science kits and mathematics instruments."},
        {"code": "EDUCATIONAL_TRAINING", "name": "Remedial Coaching / Digital Courseware", "description": "Academic tutoring and online skill licenses."},
    ],
    "HEALTHCARE": [
        {"code": "MEDICINES", "name": "Essential Prescription Medicines", "description": "Chronic and acute care essential pharmaceutical support."},
        {"code": "MEDICAL_EQUIPMENT", "name": "BP Monitor / Glucometer / Oximeter", "description": "Home diagnostic and monitoring equipment."},
        {"code": "WHEELCHAIR", "name": "Standard / Folding Wheelchair", "description": "Manual or foldable patient wheelchair."},
        {"code": "HEARING_AID", "name": "Digital Hearing Aid", "description": "Sound amplifying assistive ear device."},
        {"code": "DIAGNOSTIC_SUPPORT", "name": "Lab Test & Diagnostic Vouchers", "description": "Free pathology and radiology test coverage."},
        {"code": "MEDICAL_TREATMENT", "name": "Surgical / Specialized Care Aid", "description": "Hospitalization and procedure cost assistance."},
    ],
    "DISABILITY": [
        {"code": "WHEELCHAIR", "name": "Custom Wheelchair / Tricycle", "description": "Ergonomic mobility wheelchair for persons with disabilities."},
        {"code": "WALKING_AID", "name": "Crutches / Walking Frame / White Cane", "description": "Mobility support for visually or physically impaired."},
        {"code": "HEARING_AID", "name": "Programmable Hearing Aid Kit", "description": "Audiology-fitted hearing solution."},
        {"code": "PROSTHETIC_ORTHOTIC_DEVICE", "name": "Prosthetic Limb / Caliper Kit", "description": "Artificial limb and orthotic support gear."},
        {"code": "ASSISTIVE_TECHNOLOGY", "name": "Screen Reader / Braille Display", "description": "Assistive software and tactile hardware."},
        {"code": "REHABILITATION_SUPPORT", "name": "Physiotherapy & Speech Therapy Aid", "description": "Professional therapy and rehabilitation exercises."},
    ],
    "LIVELIHOOD": [
        {"code": "SEWING_MACHINE", "name": "Heavy Duty / Electric Sewing Machine", "description": "Tailoring and stitching equipment for micro-income."},
        {"code": "TOOL_KIT", "name": "Artisan / Carpenter / Plumber Toolkit", "description": "Trade-specific professional tools."},
        {"code": "BUSINESS_EQUIPMENT", "name": "Street Vendor Cart / Food Kiosk Kit", "description": "Vending trolley, gas stove, and display utensils."},
        {"code": "BUSINESS_STARTER_KIT", "name": "Micro-Retail Raw Material Starter Pack", "description": "Initial inventory for grocery or craft venture."},
        {"code": "SKILL_TRAINING", "name": "Vocational Apprenticeship Sponsorship", "description": "Fee support for certified vocational skills."},
        {"code": "EMPLOYMENT_SUPPORT", "name": "Job Placement & Commute Assistance", "description": "First-mile job transition and transport aid."},
    ],
    "WOMEN_EMPOWERMENT": [
        {"code": "SEWING_MACHINE", "name": "Motorized Tailoring Unit", "description": "Garment manufacturing machine for women SHGs."},
        {"code": "BUSINESS_EQUIPMENT", "name": "Food Processing / Papad / Pickle Machine", "description": "Kitchen processing units for women entrepreneurs."},
        {"code": "SKILL_TRAINING", "name": "Handicraft & Beauty Wellness Training", "description": "Professional vocational course sponsorship."},
        {"code": "ENTREPRENEURSHIP_SUPPORT", "name": "SHG Enterprise Grant Kit", "description": "Group enterprise seed tools and branding package."},
        {"code": "EMPLOYMENT_SUPPORT", "name": "Workplace Transition & Childcare Aid", "description": "Support stipend for working mothers."},
        {"code": "DIGITAL_TRAINING", "name": "Women Digital Literacy & Financial App Training", "description": "Mobile banking and digital sales coaching."},
    ],
    "CHILD_WELFARE": [
        {"code": "SCHOOL_SUPPLIES", "name": "Complete School Stationery Kit", "description": "Yearly stationery, bag, and water bottle."},
        {"code": "BOOKS_STUDY_MATERIAL", "name": "Storybooks & Learning Materials", "description": "Early childhood literacy kits."},
        {"code": "SCHOOL_UNIFORM", "name": "School Uniform & Footwear Kit", "description": "Tailored school clothes and durable shoes."},
        {"code": "EDUCATIONAL_EQUIPMENT", "name": "Play & Montessori Activity Kit", "description": "Cognitive development educational toys."},
        {"code": "LEARNING_SUPPORT", "name": "After-School Tutoring Support", "description": "Community learning center sponsorship."},
        {"code": "SPORTS_EQUIPMENT", "name": "Children Playground & Sports Gear", "description": "Recreational balls, skipping ropes, and games."},
    ],
    "ELDERLY_SUPPORT": [
        {"code": "WHEELCHAIR", "name": "Comfort Wheelchair for Seniors", "description": "Padded wheelchair with attendant brakes."},
        {"code": "WALKING_AID", "name": "Quadripod Walking Stick / Walker", "description": "Stable 4-point walking cane."},
        {"code": "MEDICAL_EQUIPMENT", "name": "Home Healthcare Oxygen / Nebulizer", "description": "Respiratory and vitals monitoring machines."},
        {"code": "HEARING_AID", "name": "Easy-Operate Senior Hearing Device", "description": "Simple knob-operated hearing amplifier."},
        {"code": "HOME_CARE_SUPPORT", "name": "Elderly Caregiver Support Voucher", "description": "Visiting nursing and hygiene assistant."},
        {"code": "MOBILITY_EQUIPMENT", "name": "Bathroom Anti-Slip & Grab Bar Kit", "description": "Home safety installation equipment."},
    ],
    "HOUSING": [
        {"code": "ROOFING_MATERIALS", "name": "Corrugated Tin / Asbestos Roofing Sheets", "description": "Weather-proof roofing panels."},
        {"code": "CONSTRUCTION_MATERIALS", "name": "Cement, Bricks & Masonry Kit", "description": "Basic building supplies for kutcha house upgrade."},
        {"code": "HOME_REPAIR_SUPPORT", "name": "Plumbing & Structural Repair Service", "description": "Leakage and wall strengthening aid."},
        {"code": "BEDS_MATTRESSES", "name": "Foldable Steel Cot & Mattress Kit", "description": "Elevated bed and hygienic foam mattress."},
        {"code": "LIGHTING_EQUIPMENT", "name": "Home Wiring & LED Fixtures", "description": "Safe residential electrical fittings."},
        {"code": "WATER_STORAGE", "name": "500L Overhead Water Storage Tank", "description": "Domestic potable water storage tank."},
    ],
    "WATER_SANITATION": [
        {"code": "WATER_FILTER", "name": "Gravity / RO Water Purifier", "description": "Household water purification filter."},
        {"code": "WATER_TANK", "name": "1000L Rain / Community Water Tank", "description": "Bulk community water storage unit."},
        {"code": "WATER_PUMP", "name": "Submersible Drinking Water Pump", "description": "Borewell and well drinking pump."},
        {"code": "TOILET_SUPPORT", "name": "Individual Household Latrine Prefab Kit", "description": "Sanitary toilet pan, door, and septic slab."},
        {"code": "SANITATION_EQUIPMENT", "name": "Drainage Cleaning & Hygiene Tools", "description": "Protective boots, gloves, and desilting tools."},
        {"code": "WASTE_MANAGEMENT_EQUIPMENT", "name": "Segregated Dustbin & Composting Bin", "description": "Solid and wet waste segregation bins."},
    ],
    "ENERGY": [
        {"code": "SOLAR_PANEL", "name": "Rooftop 100W/200W Solar PV Module", "description": "Photovoltaic panel for off-grid lighting."},
        {"code": "SOLAR_LAMP", "name": "Rechargeable Solar Study Lantern", "description": "Portable solar desk lamp with mobile charging."},
        {"code": "SOLAR_LANTERN", "name": "Emergency Multi-Light Solar Kit", "description": "Central solar battery with 3 room bulbs."},
        {"code": "BATTERY_INVERTER", "name": "Backup Inverter & Battery Pack", "description": "Power storage for essential equipment."},
        {"code": "LED_LIGHTING", "name": "Energy Efficient LED Tube & Bulb Pack", "description": "Low-power residential lighting kit."},
        {"code": "ELECTRICAL_EQUIPMENT", "name": "Clean Biomass Cookstove", "description": "Smokeless efficient wood/pellet cooking stove."},
    ],
    "DIGITAL_ACCESS": [
        {"code": "LAPTOP_DESKTOP", "name": "Refurbished Student Computer", "description": "Standard PC for digital skills and typing."},
        {"code": "TABLET", "name": "Digital Access Smart Tablet", "description": "Touchscreen tablet for accessing government schemes."},
        {"code": "SMARTPHONE", "name": "Entry-Level 4G Smartphone", "description": "Device for citizen utility apps and direct benefits."},
        {"code": "INTERNET_DEVICE", "name": "4G Wi-Fi Dongle / Router with Data Pack", "description": "High-speed community wireless connectivity."},
        {"code": "COMPUTER_ACCESSORIES", "name": "Keyboard, Mouse & Webcam Pack", "description": "Peripherals for digital learning centers."},
        {"code": "DIGITAL_LITERACY_TRAINING", "name": "Basic Computer Skills Course Voucher", "description": "Certified introductory computing training."},
    ],
    "DISASTER_RECOVERY": [
        {"code": "TEMPORARY_SHELTER", "name": "Tarpaulin & Emergency Tent Kit", "description": "Heavy-duty waterproof shelter sheets."},
        {"code": "SOLAR_LAMP", "name": "Disaster Relief Solar Flashlight", "description": "Rugged water-resistant rechargeable light."},
        {"code": "WATER_PURIFICATION_EQUIPMENT", "name": "Emergency Water Chlorine Tabs & Filters", "description": "Instant potable water purification kit."},
        {"code": "EMERGENCY_EQUIPMENT", "name": "First Aid & Disaster Survival Kit", "description": "Bandages, antiseptics, whistles, and blankets."},
        {"code": "HOUSE_REPAIR_MATERIALS", "name": "Post-Flood Reconstruction Timber & Metal", "description": "Immediate rehabilitation structural materials."},
        {"code": "LIVELIHOOD_RECOVERY_EQUIPMENT", "name": "Replacement Artisan / Trade Tools", "description": "Restoration tools for flood/cyclone victims."},
    ],
    "SKILL_DEVELOPMENT": [
        {"code": "COMPUTER_TRAINING", "name": "Software & Office Automation Kit", "description": "Courseware, guides, and typing training."},
        {"code": "SEWING_TRAINING", "name": "Tailoring & Pattern Making Kit", "description": "Scissors, measuring tape, mannequins, and fabrics."},
        {"code": "ELECTRICAL_TRAINING", "name": "Electrician Practice & Safety Toolkit", "description": "Multimeter, wire strippers, testers, and boards."},
        {"code": "WELDING_TRAINING", "name": "Arc Welding & Safety Shield Kit", "description": "Welding goggles, rods, and protective leather gear."},
        {"code": "DRIVING_TRAINING", "name": "Commercial Driver Training Sponsorship", "description": "Driving school fee and license documentation aid."},
        {"code": "ENTREPRENEURSHIP_TRAINING", "name": "Business Plan & Bookkeeping Course", "description": "Financial management course for youth."},
    ],
    "MOBILITY": [
        {"code": "BICYCLE", "name": "Student / Commuter Bicycle", "description": "Single-speed sturdy bicycle for school/work travel."},
        {"code": "WHEELCHAIR", "name": "All-Terrain Rugged Wheelchair", "description": "Heavy-duty outdoor wheelchair for rural roads."},
        {"code": "MOBILITY_AID", "name": "Specialized Quad Cane / Rollator Walker", "description": "Wheeled walker with handbrakes and seat."},
        {"code": "TRICYCLE", "name": "Hand-Cranked Mobility Tricycle", "description": "Three-wheel hand cycle for disabled adults."},
        {"code": "ACCESSIBLE_TRANSPORTATION", "name": "Public Transit Commuter Travel Pass", "description": "Annual bus/train pass subsidy."},
        {"code": "VEHICLE_REPAIR_SUPPORT", "name": "Invalid Carriage Modification Kit", "description": "Retrofitting two-wheelers with balance wheels."},
    ],
    "ENVIRONMENT": [
        {"code": "SAPLINGS", "name": "Fruit & Native Tree Saplings Pack (50x)", "description": "Neem, teak, mango, and guava seedlings."},
        {"code": "GARDENING_EQUIPMENT", "name": "Community Nursery Toolset", "description": "Watering cans, pruning shears, and trowels."},
        {"code": "WASTE_MANAGEMENT_EQUIPMENT", "name": "Twin Bin Community Waste Collector", "description": "Wet and dry recycling collection bins."},
        {"code": "RECYCLING_EQUIPMENT", "name": "Plastic Shredder / Baler Tool", "description": "Small-scale community recycling implement."},
        {"code": "COMPOSTING_EQUIPMENT", "name": "Aerobic Kitchen Waste Compost Unit", "description": "Bokashi / vermicompost bin for organic waste."},
        {"code": "RAINWATER_HARVESTING_EQUIPMENT", "name": "Rooftop Filter & First Flush Diverter", "description": "Rainwater collection filtration unit."},
    ],
    "SPORTS": [
        {"code": "SPORTS_EQUIPMENT", "name": "Multisport Balls & Cones Kit", "description": "Volleyballs, basketballs, cones, and pumps."},
        {"code": "SPORTS_SHOES", "name": "Athletic Running Shoes & Socks", "description": "Non-marking training footwear for youth."},
        {"code": "SPORTS_UNIFORM", "name": "Team Jersey & Shorts Set (11x)", "description": "Breathable team sports kit."},
        {"code": "CRICKET_EQUIPMENT", "name": "Full Cricket Kit (Bats, Pads, Balls, Stumps)", "description": "Complete leather and tennis cricket set."},
        {"code": "FOOTBALL_EQUIPMENT", "name": "FIFA Standard Footballs & Goal Nets", "description": "Tournament quality football equipment."},
        {"code": "SPORTS_TRAINING", "name": "Grassroots Coach Coaching Support", "description": "Sponsorship for physical education instructor."},
    ],
}
