"""Demo NGO seed definitions (Marked as [DEMO/SEED DATA])."""

SEED_NGOS = [
    {
        "ngo_code": "NGO001",
        "ngo_name": "Helping Hands Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2021-MH-001",
        "contact_person": "Rajesh Sharma",
        "phone": "+91-9876543210",
        "state": "Maharashtra",
        "district": "Pune",
        "address": "12 Shanti Nagar, Kothrud, Pune",
        "description": "Fictional demo NGO providing education, laptops, tablets, and medical healthcare equipment.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "EDUCATION", "req": "LAPTOP_DESKTOP", "qty": 40, "unit": "laptops", "dur_val": 4, "dur_unit": "DAYS"},
            {"category": "EDUCATION", "req": "TABLET", "qty": 80, "unit": "tablets", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "HEALTHCARE", "req": "WHEELCHAIR", "qty": 25, "unit": "wheelchairs", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "HEALTHCARE", "req": "MEDICINES", "qty": 500, "unit": "kits", "dur_val": 1, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Maharashtra", "district": "Pune", "area": "Kothrud"},
            {"state": "Maharashtra", "district": "Pune", "area": "Hadapsar"},
            {"state": "Maharashtra", "district": "Mumbai", "area": "Andheri"},
            {"state": "Karnataka", "district": "Bengaluru Urban", "area": "Whitefield"},
        ],
        "historical_contributions": [
            {"category": "EDUCATION", "req": "LAPTOP_DESKTOP", "qty": 15, "unit": "laptops", "beneficiaries": 15, "on_time": True, "days_ago": 20},
            {"category": "HEALTHCARE", "req": "WHEELCHAIR", "qty": 10, "unit": "wheelchairs", "beneficiaries": 10, "on_time": True, "days_ago": 15},
            {"category": "EDUCATION", "req": "TABLET", "qty": 20, "unit": "tablets", "beneficiaries": 20, "on_time": True, "days_ago": 8},
        ],
    },
    {
        "ngo_code": "NGO002",
        "ngo_name": "Rural Development Trust [DEMO/SEED DATA]",
        "registration_number": "REG-2020-KA-002",
        "contact_person": "Suresh Gowda",
        "phone": "+91-9876543211",
        "state": "Karnataka",
        "district": "Bengaluru Urban",
        "address": "45 Green Layout, Indiranagar, Bengaluru",
        "description": "Fictional demo NGO dedicated to agricultural seeds, farming implements, and clean solar energy.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "AGRICULTURE", "req": "SEEDS", "qty": 200, "unit": "bags", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "AGRICULTURE", "req": "IRRIGATION_EQUIPMENT", "qty": 30, "unit": "kits", "dur_val": 5, "dur_unit": "DAYS"},
            {"category": "ENERGY", "req": "SOLAR_LAMP", "qty": 150, "unit": "lamps", "dur_val": 3, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Karnataka", "district": "Bengaluru Urban", "area": "Indiranagar"},
            {"state": "Karnataka", "district": "Mysuru", "area": "Gokulam"},
            {"state": "Tamil Nadu", "district": "Chennai", "area": "Adyar"},
        ],
        "historical_contributions": [
            {"category": "AGRICULTURE", "req": "SEEDS", "qty": 100, "unit": "bags", "beneficiaries": 50, "on_time": True, "days_ago": 25},
            {"category": "ENERGY", "req": "SOLAR_LAMP", "qty": 40, "unit": "lamps", "beneficiaries": 40, "on_time": False, "days_ago": 12},
        ],
    },
    {
        "ngo_code": "NGO003",
        "ngo_name": "Fisher Welfare Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2019-TN-003",
        "contact_person": "M. Selvam",
        "phone": "+91-9876543212",
        "state": "Tamil Nadu",
        "district": "Nagapattinam",
        "address": "88 Harbor Road, Velankanni, Nagapattinam",
        "description": "Fictional demo NGO supporting coastal fishermen with nylon fishing nets, boats, and marine safety gear.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "FISHERIES", "req": "FISHING_NET", "qty": 50, "unit": "nets", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "FISHERIES", "req": "FISHING_BOAT", "qty": 5, "unit": "boats", "dur_val": 14, "dur_unit": "DAYS"},
            {"category": "FISHERIES", "req": "SAFETY_EQUIPMENT", "qty": 100, "unit": "jackets", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "FISHERIES", "req": "FISH_STORAGE_EQUIPMENT", "qty": 40, "unit": "ice-boxes", "dur_val": 4, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Tamil Nadu", "district": "Nagapattinam", "area": "Velankanni"},
            {"state": "Tamil Nadu", "district": "Nagapattinam", "area": "Nagore"},
            {"state": "Tamil Nadu", "district": "Cuddalore", "area": "Port Nova"},
            {"state": "Kerala", "district": "Ernakulam", "area": "Kochi Harbor"},
        ],
        "historical_contributions": [
            {"category": "FISHERIES", "req": "FISHING_NET", "qty": 30, "unit": "nets", "beneficiaries": 30, "on_time": True, "days_ago": 30},
            {"category": "FISHERIES", "req": "SAFETY_EQUIPMENT", "qty": 50, "unit": "jackets", "beneficiaries": 50, "on_time": True, "days_ago": 18},
            {"category": "FISHERIES", "req": "FISH_STORAGE_EQUIPMENT", "qty": 20, "unit": "ice-boxes", "beneficiaries": 20, "on_time": True, "days_ago": 5},
        ],
    },
    {
        "ngo_code": "NGO004",
        "ngo_name": "Care India Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2018-DL-004",
        "contact_person": "Pooja Verma",
        "phone": "+91-9876543213",
        "state": "Delhi",
        "district": "New Delhi",
        "address": "21 Barakhamba Road, Connaught Place, New Delhi",
        "description": "Fictional demo NGO providing health diagnostics, student laptops, and disability assistive tech across north India.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "HEALTHCARE", "req": "MEDICINES", "qty": 800, "unit": "kits", "dur_val": 1, "dur_unit": "DAYS"},
            {"category": "EDUCATION", "req": "LAPTOP_DESKTOP", "qty": 35, "unit": "laptops", "dur_val": 5, "dur_unit": "DAYS"},
            {"category": "DISABILITY", "req": "HEARING_AID", "qty": 50, "unit": "kits", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "DISABILITY", "req": "WHEELCHAIR", "qty": 30, "unit": "wheelchairs", "dur_val": 2, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Delhi", "district": "New Delhi", "area": "Connaught Place"},
            {"state": "Uttar Pradesh", "district": "Noida", "area": "Sector 62"},
            {"state": "Haryana", "district": "Gurugram", "area": "Cyber City"},
        ],
        "historical_contributions": [
            {"category": "HEALTHCARE", "req": "MEDICINES", "qty": 300, "unit": "kits", "beneficiaries": 300, "on_time": True, "days_ago": 40},
            {"category": "DISABILITY", "req": "HEARING_AID", "qty": 25, "unit": "kits", "beneficiaries": 25, "on_time": True, "days_ago": 22},
        ],
    },
    {
        "ngo_code": "NGO005",
        "ngo_name": "Bright Future Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2022-GJ-005",
        "contact_person": "Anil Patel",
        "phone": "+91-9876543214",
        "state": "Gujarat",
        "district": "Ahmedabad",
        "address": "104 Ashram Road, Navrangpura, Ahmedabad",
        "description": "Fictional demo NGO providing school books, student laptops, and digital literacy devices.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "EDUCATION", "req": "LAPTOP_DESKTOP", "qty": 70, "unit": "laptops", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "EDUCATION", "req": "TABLET", "qty": 60, "unit": "tablets", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "EDUCATION", "req": "BOOKS_STUDY_MATERIAL", "qty": 1000, "unit": "books", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "EDUCATION", "req": "SCHOOL_SUPPLIES", "qty": 500, "unit": "kits", "dur_val": 1, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Gujarat", "district": "Ahmedabad", "area": "Navrangpura"},
            {"state": "Gujarat", "district": "Surat", "area": "Varachha"},
            {"state": "Rajasthan", "district": "Jaipur", "area": "Malviya Nagar"},
        ],
        "historical_contributions": [
            {"category": "EDUCATION", "req": "LAPTOP_DESKTOP", "qty": 30, "unit": "laptops", "beneficiaries": 30, "on_time": True, "days_ago": 19},
            {"category": "EDUCATION", "req": "BOOKS_STUDY_MATERIAL", "qty": 400, "unit": "books", "beneficiaries": 200, "on_time": True, "days_ago": 11},
        ],
    },
    {
        "ngo_code": "NGO006",
        "ngo_name": "Women Rise Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2021-WB-006",
        "contact_person": "Sunita Banerjee",
        "phone": "+91-9876543215",
        "state": "West Bengal",
        "district": "Kolkata",
        "address": "56 Park Street, Kolkata",
        "description": "Fictional demo NGO supporting women livelihoods through motorized sewing machines and skill training.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "WOMEN_EMPOWERMENT", "req": "SEWING_MACHINE", "qty": 90, "unit": "machines", "dur_val": 4, "dur_unit": "DAYS"},
            {"category": "LIVELIHOOD", "req": "SEWING_MACHINE", "qty": 60, "unit": "machines", "dur_val": 4, "dur_unit": "DAYS"},
            {"category": "WOMEN_EMPOWERMENT", "req": "BUSINESS_EQUIPMENT", "qty": 40, "unit": "kits", "dur_val": 6, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "West Bengal", "district": "Kolkata", "area": "Park Street"},
            {"state": "West Bengal", "district": "Howrah", "area": "Shibpur"},
            {"state": "Odisha", "district": "Bhubaneswar", "area": "Saheed Nagar"},
        ],
        "historical_contributions": [
            {"category": "WOMEN_EMPOWERMENT", "req": "SEWING_MACHINE", "qty": 45, "unit": "machines", "beneficiaries": 45, "on_time": True, "days_ago": 35},
        ],
    },
    {
        "ngo_code": "NGO007",
        "ngo_name": "Green Earth Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2017-TS-007",
        "contact_person": "K. Srinivas",
        "phone": "+91-9876543216",
        "state": "Telangana",
        "district": "Hyderabad",
        "address": "19 Jubilee Hills, Hyderabad",
        "description": "Fictional demo NGO focusing on sapling distribution, environmental rainwater harvesting, and solar lighting.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "ENVIRONMENT", "req": "SAPLINGS", "qty": 2000, "unit": "plants", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "ENVIRONMENT", "req": "RAINWATER_HARVESTING_EQUIPMENT", "qty": 25, "unit": "filters", "dur_val": 7, "dur_unit": "DAYS"},
            {"category": "ENERGY", "req": "SOLAR_PANEL", "qty": 30, "unit": "panels", "dur_val": 5, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Telangana", "district": "Hyderabad", "area": "Jubilee Hills"},
            {"state": "Andhra Pradesh", "district": "Visakhapatnam", "area": "MVP Colony"},
        ],
        "historical_contributions": [
            {"category": "ENVIRONMENT", "req": "SAPLINGS", "qty": 800, "unit": "plants", "beneficiaries": 100, "on_time": True, "days_ago": 28},
        ],
    },
    {
        "ngo_code": "NGO008",
        "ngo_name": "Digital Hope Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2022-TG-008",
        "contact_person": "Deepak Reddy",
        "phone": "+91-9876543217",
        "state": "Telangana",
        "district": "Hyderabad",
        "address": "77 Hitech City, Madhapur, Hyderabad",
        "description": "Fictional demo NGO delivering student computers, internet 4G devices, and digital literacy courseware.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "DIGITAL_ACCESS", "req": "LAPTOP_DESKTOP", "qty": 55, "unit": "laptops", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "DIGITAL_ACCESS", "req": "TABLET", "qty": 110, "unit": "tablets", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "DIGITAL_ACCESS", "req": "INTERNET_DEVICE", "qty": 150, "unit": "dongles", "dur_val": 1, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Telangana", "district": "Hyderabad", "area": "Madhapur"},
            {"state": "Karnataka", "district": "Bengaluru Urban", "area": "Electronic City"},
        ],
        "historical_contributions": [
            {"category": "DIGITAL_ACCESS", "req": "TABLET", "qty": 60, "unit": "tablets", "beneficiaries": 60, "on_time": True, "days_ago": 14},
        ],
    },
    {
        "ngo_code": "NGO009",
        "ngo_name": "Coastal Livelihood Trust [DEMO/SEED DATA]",
        "registration_number": "REG-2020-KL-009",
        "contact_person": "Antony Joseph",
        "phone": "+91-9876543218",
        "state": "Kerala",
        "district": "Ernakulam",
        "address": "12 Fort Kochi, Kochi",
        "description": "Fictional demo NGO providing coastal fisheries gear, fishing nets, boat motors, and marine lifejackets.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "FISHERIES", "req": "FISHING_NET", "qty": 45, "unit": "nets", "dur_val": 4, "dur_unit": "DAYS"},
            {"category": "FISHERIES", "req": "BOAT_ENGINE", "qty": 10, "unit": "engines", "dur_val": 10, "dur_unit": "DAYS"},
            {"category": "FISHERIES", "req": "SAFETY_EQUIPMENT", "qty": 80, "unit": "jackets", "dur_val": 2, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Kerala", "district": "Ernakulam", "area": "Fort Kochi"},
            {"state": "Kerala", "district": "Alappuzha", "area": "Kuttanad"},
            {"state": "Tamil Nadu", "district": "Nagapattinam", "area": "Nagapattinam Port"},
            {"state": "Tamil Nadu", "district": "Kanyakumari", "area": "Colachel"},
        ],
        "historical_contributions": [
            {"category": "FISHERIES", "req": "FISHING_NET", "qty": 20, "unit": "nets", "beneficiaries": 20, "on_time": True, "days_ago": 21},
        ],
    },
    {
        "ngo_code": "NGO010",
        "ngo_name": "Health Support Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2016-TN-010",
        "contact_person": "Dr. V. Natarajan",
        "phone": "+91-9876543219",
        "state": "Tamil Nadu",
        "district": "Chennai",
        "address": "9 Anna Salai, T. Nagar, Chennai",
        "description": "Fictional demo NGO providing vital medicines, senior walking aids, diagnostic support, and home monitoring equipment.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "HEALTHCARE", "req": "MEDICINES", "qty": 1200, "unit": "kits", "dur_val": 1, "dur_unit": "DAYS"},
            {"category": "HEALTHCARE", "req": "DIAGNOSTIC_SUPPORT", "qty": 300, "unit": "vouchers", "dur_val": 1, "dur_unit": "DAYS"},
            {"category": "ELDERLY_SUPPORT", "req": "WALKING_AID", "qty": 75, "unit": "sticks", "dur_val": 2, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Tamil Nadu", "district": "Chennai", "area": "T. Nagar"},
            {"state": "Tamil Nadu", "district": "Madurai", "area": "KK Nagar"},
        ],
        "historical_contributions": [
            {"category": "HEALTHCARE", "req": "MEDICINES", "qty": 500, "unit": "kits", "beneficiaries": 500, "on_time": True, "days_ago": 30},
        ],
    },
    {
        "ngo_code": "NGO011",
        "ngo_name": "Rural Skills Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2021-UP-011",
        "contact_person": "Ramesh Yadav",
        "phone": "+91-9876543220",
        "state": "Uttar Pradesh",
        "district": "Lucknow",
        "address": "33 Hazratganj, Lucknow",
        "description": "Fictional demo NGO providing vocational tools, electrical repair kits, and artisan livelihood packs.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "LIVELIHOOD", "req": "TOOL_KIT", "qty": 85, "unit": "kits", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "SKILL_DEVELOPMENT", "req": "ELECTRICAL_TRAINING", "qty": 50, "unit": "kits", "dur_val": 5, "dur_unit": "DAYS"},
            {"category": "SKILL_DEVELOPMENT", "req": "WELDING_TRAINING", "qty": 30, "unit": "kits", "dur_val": 7, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Uttar Pradesh", "district": "Lucknow", "area": "Hazratganj"},
            {"state": "Uttar Pradesh", "district": "Kanpur Nagar", "area": "Civil Lines"},
        ],
        "historical_contributions": [
            {"category": "LIVELIHOOD", "req": "TOOL_KIT", "qty": 35, "unit": "kits", "beneficiaries": 35, "on_time": True, "days_ago": 16},
        ],
    },
    {
        "ngo_code": "NGO012",
        "ngo_name": "Child Development Trust [DEMO/SEED DATA]",
        "registration_number": "REG-2019-RJ-012",
        "contact_person": "Meena Rathore",
        "phone": "+91-9876543221",
        "state": "Rajasthan",
        "district": "Jaipur",
        "address": "77 MI Road, Jaipur",
        "description": "Fictional demo NGO providing school uniforms, stationery bags, and early childhood learning support.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "CHILD_WELFARE", "req": "SCHOOL_UNIFORM", "qty": 400, "unit": "uniforms", "dur_val": 4, "dur_unit": "DAYS"},
            {"category": "CHILD_WELFARE", "req": "SCHOOL_SUPPLIES", "qty": 600, "unit": "kits", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "CHILD_WELFARE", "req": "BOOKS_STUDY_MATERIAL", "qty": 500, "unit": "books", "dur_val": 2, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Rajasthan", "district": "Jaipur", "area": "MI Road"},
            {"state": "Rajasthan", "district": "Jodhpur", "area": "Ratanada"},
        ],
        "historical_contributions": [
            {"category": "CHILD_WELFARE", "req": "SCHOOL_UNIFORM", "qty": 150, "unit": "uniforms", "beneficiaries": 150, "on_time": True, "days_ago": 22},
        ],
    },
    {
        "ngo_code": "NGO013",
        "ngo_name": "Inclusive Life Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2018-MH-013",
        "contact_person": "Vikram Desai",
        "phone": "+91-9876543222",
        "state": "Maharashtra",
        "district": "Mumbai",
        "address": "202 Bandra West, Mumbai",
        "description": "Fictional demo NGO delivering custom wheelchairs, prosthetic limb calipers, and mobility assistive tech.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "DISABILITY", "req": "WHEELCHAIR", "qty": 40, "unit": "wheelchairs", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "DISABILITY", "req": "PROSTHETIC_ORTHOTIC_DEVICE", "qty": 20, "unit": "kits", "dur_val": 14, "dur_unit": "DAYS"},
            {"category": "MOBILITY", "req": "TRICYCLE", "qty": 25, "unit": "tricycles", "dur_val": 5, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Maharashtra", "district": "Mumbai", "area": "Bandra"},
            {"state": "Maharashtra", "district": "Thane", "area": "Naupada"},
        ],
        "historical_contributions": [
            {"category": "DISABILITY", "req": "WHEELCHAIR", "qty": 18, "unit": "wheelchairs", "beneficiaries": 18, "on_time": True, "days_ago": 17},
        ],
    },
    {
        "ngo_code": "NGO014",
        "ngo_name": "Clean Water Initiative [DEMO/SEED DATA]",
        "registration_number": "REG-2020-OR-014",
        "contact_person": "Pradeep Mohapatra",
        "phone": "+91-9876543223",
        "state": "Odisha",
        "district": "Bhubaneswar",
        "address": "40 Chandrasekharpur, Bhubaneswar",
        "description": "Fictional demo NGO providing water purifiers, overhead tanks, and sanitation toilet kits.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "WATER_SANITATION", "req": "WATER_FILTER", "qty": 120, "unit": "filters", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "WATER_SANITATION", "req": "WATER_TANK", "qty": 30, "unit": "tanks", "dur_val": 5, "dur_unit": "DAYS"},
            {"category": "WATER_SANITATION", "req": "TOILET_SUPPORT", "qty": 40, "unit": "kits", "dur_val": 7, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Odisha", "district": "Bhubaneswar", "area": "Chandrasekharpur"},
            {"state": "Odisha", "district": "Puri", "area": "Grand Road"},
        ],
        "historical_contributions": [
            {"category": "WATER_SANITATION", "req": "WATER_FILTER", "qty": 50, "unit": "filters", "beneficiaries": 200, "on_time": True, "days_ago": 26},
        ],
    },
    {
        "ngo_code": "NGO015",
        "ngo_name": "Solar Future Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2021-MP-015",
        "contact_person": "Alok Mishra",
        "phone": "+91-9876543224",
        "state": "Madhya Pradesh",
        "district": "Bhopal",
        "address": "67 MP Nagar, Bhopal",
        "description": "Fictional demo NGO providing off-grid solar lamps, lanterns, and rooftop solar panels for rural homes.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "ENERGY", "req": "SOLAR_LAMP", "qty": 250, "unit": "lamps", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "ENERGY", "req": "SOLAR_LANTERN", "qty": 100, "unit": "kits", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "ENERGY", "req": "SOLAR_PANEL", "qty": 45, "unit": "panels", "dur_val": 6, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Madhya Pradesh", "district": "Bhopal", "area": "MP Nagar"},
            {"state": "Madhya Pradesh", "district": "Indore", "area": "Vijay Nagar"},
        ],
        "historical_contributions": [
            {"category": "ENERGY", "req": "SOLAR_LAMP", "qty": 110, "unit": "lamps", "beneficiaries": 110, "on_time": True, "days_ago": 15},
        ],
    },
    {
        "ngo_code": "NGO016",
        "ngo_name": "Farmers Support Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2017-PB-016",
        "contact_person": "Harpreet Singh",
        "phone": "+91-9876543225",
        "state": "Punjab",
        "district": "Ludhiana",
        "address": "15 GT Road, Ludhiana",
        "description": "Fictional demo NGO providing agricultural seeds, mini water pumps, and organic farming implements.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "AGRICULTURE", "req": "SEEDS", "qty": 300, "unit": "bags", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "AGRICULTURE", "req": "WATER_PUMP", "qty": 20, "unit": "pumps", "dur_val": 5, "dur_unit": "DAYS"},
            {"category": "AGRICULTURE", "req": "FARMING_TOOLS", "qty": 150, "unit": "sets", "dur_val": 3, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Punjab", "district": "Ludhiana", "area": "GT Road"},
            {"state": "Punjab", "district": "Amritsar", "area": "Ranjit Avenue"},
            {"state": "Haryana", "district": "Ambala", "area": "Model Town"},
        ],
        "historical_contributions": [
            {"category": "AGRICULTURE", "req": "SEEDS", "qty": 140, "unit": "bags", "beneficiaries": 70, "on_time": True, "days_ago": 32},
        ],
    },
    {
        "ngo_code": "NGO017",
        "ngo_name": "Youth Sports Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2022-HR-017",
        "contact_person": "Virender Hooda",
        "phone": "+91-9876543226",
        "state": "Haryana",
        "district": "Rohtak",
        "address": "89 Sports Complex Road, Rohtak",
        "description": "Fictional demo NGO providing sports kits, running shoes, cricket gear, and football equipment.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "SPORTS", "req": "SPORTS_EQUIPMENT", "qty": 100, "unit": "kits", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "SPORTS", "req": "SPORTS_SHOES", "qty": 150, "unit": "pairs", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "SPORTS", "req": "CRICKET_EQUIPMENT", "qty": 40, "unit": "kits", "dur_val": 4, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Haryana", "district": "Rohtak", "area": "Model Town"},
            {"state": "Delhi", "district": "North Delhi", "area": "Rohini"},
        ],
        "historical_contributions": [
            {"category": "SPORTS", "req": "SPORTS_EQUIPMENT", "qty": 40, "unit": "kits", "beneficiaries": 200, "on_time": True, "days_ago": 18},
        ],
    },
    {
        "ngo_code": "NGO018",
        "ngo_name": "Shelter Support Trust [DEMO/SEED DATA]",
        "registration_number": "REG-2018-AS-018",
        "contact_person": "Bhaskar Barua",
        "phone": "+91-9876543227",
        "state": "Assam",
        "district": "Guwahati",
        "address": "11 GS Road, Dispur, Guwahati",
        "description": "Fictional demo NGO providing roofing sheets, cots/mattresses, and post-flood temporary shelter kits in the North East.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "HOUSING", "req": "ROOFING_MATERIALS", "qty": 180, "unit": "sheets", "dur_val": 4, "dur_unit": "DAYS"},
            {"category": "HOUSING", "req": "BEDS_MATTRESSES", "qty": 70, "unit": "sets", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "DISASTER_RECOVERY", "req": "TEMPORARY_SHELTER", "qty": 90, "unit": "tents", "dur_val": 2, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Assam", "district": "Guwahati", "area": "Dispur"},
            {"state": "Assam", "district": "Dibrugarh", "area": "Jalan Nagar"},
        ],
        "historical_contributions": [
            {"category": "HOUSING", "req": "ROOFING_MATERIALS", "qty": 80, "unit": "sheets", "beneficiaries": 40, "on_time": True, "days_ago": 29},
        ],
    },
    {
        "ngo_code": "NGO019",
        "ngo_name": "Women & Child Development Trust [DEMO/SEED DATA]",
        "registration_number": "REG-2021-BR-019",
        "contact_person": "Anjali Kumari",
        "phone": "+91-9876543228",
        "state": "Bihar",
        "district": "Patna",
        "address": "4 Bailey Road, Patna",
        "description": "Fictional demo NGO providing tailoring machines, children school uniforms, and community learning support.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "WOMEN_EMPOWERMENT", "req": "SEWING_MACHINE", "qty": 50, "unit": "machines", "dur_val": 4, "dur_unit": "DAYS"},
            {"category": "CHILD_WELFARE", "req": "SCHOOL_UNIFORM", "qty": 200, "unit": "uniforms", "dur_val": 3, "dur_unit": "DAYS"},
            {"category": "EDUCATION", "req": "SCHOOL_SUPPLIES", "qty": 300, "unit": "kits", "dur_val": 2, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Bihar", "district": "Patna", "area": "Bailey Road"},
            {"state": "Bihar", "district": "Gaya", "area": "Civil Lines"},
        ],
        "historical_contributions": [
            {"category": "WOMEN_EMPOWERMENT", "req": "SEWING_MACHINE", "qty": 25, "unit": "machines", "beneficiaries": 25, "on_time": True, "days_ago": 13},
        ],
    },
    {
        "ngo_code": "NGO020",
        "ngo_name": "Community Care Foundation [DEMO/SEED DATA]",
        "registration_number": "REG-2022-AP-020",
        "contact_person": "V. Ramachandra",
        "phone": "+91-9876543229",
        "state": "Andhra Pradesh",
        "district": "Vijayawada",
        "address": "25 MG Road, Vijayawada",
        "description": "Fictional demo NGO providing senior walking aids, home care equipment, student bicycles, and water purifiers.",
        "registration_status": "APPROVED",
        "services": [
            {"category": "ELDERLY_SUPPORT", "req": "WALKING_AID", "qty": 60, "unit": "sticks", "dur_val": 2, "dur_unit": "DAYS"},
            {"category": "MOBILITY", "req": "BICYCLE", "qty": 40, "unit": "bicycles", "dur_val": 4, "dur_unit": "DAYS"},
            {"category": "WATER_SANITATION", "req": "WATER_FILTER", "qty": 70, "unit": "filters", "dur_val": 3, "dur_unit": "DAYS"},
        ],
        "coverage": [
            {"state": "Andhra Pradesh", "district": "Vijayawada", "area": "MG Road"},
            {"state": "Andhra Pradesh", "district": "Guntur", "area": "Brodipet"},
        ],
        "historical_contributions": [
            {"category": "MOBILITY", "req": "BICYCLE", "qty": 20, "unit": "bicycles", "beneficiaries": 20, "on_time": True, "days_ago": 19},
        ],
    },
]
